export const config = {
  prod: {
    spaceId: '',
    secretCode: 'secretcode',
    shareURL: 'https://www.exentriq.com/',
    shareMessage: "Let's work togheter!Getting started with the Exentriq Talk",
    URL_DEFAULT_TALK: 'https://talk-stage.exentriq.com',
    URL_EXENTRIQ_HOST: 'https://stage.exentriq.com/JSON-RPC',
    METHOD_AUTH_GUARDIAN_LOGIN: 'auth.login',
    APP_NAME: 'talk',
    URL_EXENTRIQ_FEEDSERVICE: 'https://www.exentriq.com/FeedService',
    URL_MEET: 'https://dev001exe.exentriq.com',
    URL_REJECT_MEET_INVITE:
      'https://talk-stage.exentriq.com/api/rejectMeetInvite',
    BUS_NOTIFICATION: 'ws://bus.stage.exentriq.com:1880/ws/notification',
    EXENTRIQ_AVATAR_URL: 'https://stage.exentriq.com/AvatarService?username=',
  },
  stage: {
    spaceId: '',
    secretCode: 'secretcode',
    shareURL: 'https://www.exentriq.com/',
    shareMessage: "Let's work togheter!Getting started with the Exentriq Talk",
    URL_DEFAULT_TALK: 'https://talk-stage.exentriq.com',
    URL_EXENTRIQ_HOST: 'https://stage.exentriq.com/JSON-RPC',
    METHOD_AUTH_GUARDIAN_LOGIN: 'auth.login',
    APP_NAME: 'talk',
    URL_EXENTRIQ_FEEDSERVICE: 'https://www.exentriq.com/FeedService',
    URL_MEET: 'https://dev001exe.exentriq.com',
    URL_REJECT_MEET_INVITE:
      'https://talk-stage.exentriq.com/api/rejectMeetInvite',
    BUS_NOTIFICATION: 'ws://bus.stage.exentriq.com:1880/ws/notification',
    EXENTRIQ_AVATAR_URL: 'https://stage.exentriq.com/AvatarService?username=',
  },
  local: {
    spaceId: '',
    secretCode: 'secretcode',
    shareURL: 'https://www.exentriq.com/',
    shareMessage: "Let's work togheter!Getting started with the Exentriq Talk",
    URL_DEFAULT_TALK: 'https://talk-stage.exentriq.com',
    URL_EXENTRIQ_HOST: 'https://stage.exentriq.com/JSON-RPC',
    METHOD_AUTH_GUARDIAN_LOGIN: 'auth.login',
    APP_NAME: 'talk',
    URL_EXENTRIQ_FEEDSERVICE: 'https://www.exentriq.com/FeedService',
    URL_MEET: 'https://dev001exe.exentriq.com',
    URL_REJECT_MEET_INVITE:
      'https://talk-stage.exentriq.com/api/rejectMeetInvite',
    BUS_NOTIFICATION: 'ws://bus.stage.exentriq.com:1880/ws/notification',
    EXENTRIQ_AVATAR_URL: 'https://stage.exentriq.com/AvatarService?username=',
  },
};
